---
title: "Cover Letter"
---

September 30, 2023

Dear Editor-in-Chief: Prof. Adrian Aldcroft,

We kindly request your consideration of the manuscript entitled "Corticosteroids for improving outcomes in women with HELLP syndrome: an updated systematic review and meta-analysis" for publishing in BMJ Open.

This study aimed to assess the benefits and harms of corticosteroids versus placebo in HELLP syndrome. The work is critically warranted to update the evidence required for the adaptation process for the national recommendations for the management of severe preeclampsia. The guideline development group identified eleven priority questions. One the priority questions pertains to the administration of corticosteroids in HELLP syndrome. An update of the currently available synthesized evidence, published in 2010, is mandatory. Rigorous methods were followed to provide an up-to-date synthesis of best available evidence for this critical clinical question. The results could interest healthcare providers, administrators and decision-makers worldwide.

This manuscript contains an original work and is not under consideration by any other journal. All authors approved the manuscript and this submission.

All authors completed the ICMJE form for disclosure of competing interests. Given the long list of authors, we upload them as supplementary material. Please do not hesitate to let us know if you prefer to handle it differently.

Thank you for receiving our manuscript and considering it for peer review. We look forward to hearing from you.

Sincerely,
